
name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      my_inputs:
        description: 'A custom description'
        required: false
        default: 'default_value'
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 25432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Grant Execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify

#      - if: ${{github.refs == 'refs/heads/master'}}
      - name: Build and Publish Docker Image
        run:  ./mvnw clean package spring-boot:build-image -DskipTests
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#          echo "${{secrets.DOCKER_PASSWORD}}"| docker login --username ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: push docker image
        run:  docker push ${{secrets.DOCKER_USERNAME}}/bookmarks-api

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
